# Generated by Django 3.0.5 on 2020-07-09 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_Published', models.BooleanField(default=True)),
                ('q_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
