# Generated by Django 3.0.5 on 2020-07-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='bedrooms',
        ),
    ]
