# Generated by Django 3.0.5 on 2020-07-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='qcode',
            field=models.IntegerField(),
        ),
    ]
